Models/BrightIdea.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BrightIdeas.Models
{
    public class BrightIdea
    {
        [Key] // Primary Key
        public int BrightIdeaId { get; set; }

        // Foreign Key 
        public int UserId { get; set; }
        
        // Navigation property for the relationship
        public User Author {get; set; } // 1 user related to each Post
        public List<Like> Likes { get; set; } // 1 Post : M votes relationship

        [Required]
        [MinLength(5, ErrorMessage = "Must be more than 5 characters.")]
        public string Content { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;

    }
}

Controllers/BrightIdeaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BrightIdeas.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BrightIdeas.Controllers
{
    public class BrightIdeaController : Controller
    {
        private BrightIdeasContext _db;
        private int? _uid
        {
            get
            {
                return HttpContext.Session.GetInt32("UserId");
            }
        }
        private bool _isLoggedIn
        {
            get
            {
                int? uid = _uid;

                if (uid != null)
                {
                    User loggedInUser =
                        _db.Users.FirstOrDefault(u => u.UserId == uid);

                    HttpContext.Session
                        .SetString("FullName", loggedInUser.FullName());
                }
                return uid != null;
            }
        }

        public BrightIdeaController(BrightIdeasContext context)
        {
            _db = context;
        }

        [HttpGet("brightidea/all")]
        public IActionResult All()
        {
            int? uid = _uid;

            if (!_isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            List<BrightIdea> allBrightIdea = _db.BrightIdea
                .Include(brightidea => brightidea.Author)
                .Include(brightidea => brightidea.Likes)
                .ThenInclude(l => l.Liker).ToList();

            // Add ViewBag lines only before return View
            ViewBag.FullName = HttpContext.Session.GetString("FullName");
            ViewBag.Uid = _uid;
            return View(allBrightIdea);
        }

        [HttpGet("brightidea/idforaliasdetails/{idforaliasdetails}")]
        public IActionResult AliasDetails(int idforaliasdetails)
        {
            BrightIdea thisselectedBrightIdea = _db.BrightIdea
                .Include(thisbrightidea => thisbrightidea.Author)
                .FirstOrDefault(b => b.BrightIdeaId == idforaliasdetails);

            // in case user manually types URL
            if (thisselectedBrightIdea == null)
                RedirectToAction("All");

            ViewBag.Uid = _uid;
            return View(thisselectedBrightIdea);
        }

        [HttpGet("brightidea/idforlikersdetails/{idforlikersdetails}")]
        public IActionResult LikersDetails(int idforlikersdetails)
        {
            BrightIdea thatselectedBrightIdea = _db.BrightIdea
                .Include(thatbrightidea => thatbrightidea.Author)
                .Include(thatbrightidea => thatbrightidea.Likes)
                .Include(thatbrightidea => thatbrightidea.Content)
                .FirstOrDefault(b => b.BrightIdeaId == idforlikersdetails);

            // in case user manually types URL
            if (thatselectedBrightIdea == null)
                RedirectToAction("All");

            ViewBag.Uid = _uid;
            return View(thatselectedBrightIdea);
        }

        [HttpGet("brightidea/new")]
        public IActionResult New()
        {
            return View();
        }

        [HttpPost("brightidea/create")]
        public IActionResult Create(BrightIdea newBrightIdea)
        {

            if (ModelState.IsValid)
            {
                if (_uid != null)
                {
                    newBrightIdea.UserId = (int)_uid;

                    _db.BrightIdea.Add(newBrightIdea);
                    _db.SaveChanges();
                    return RedirectToAction("All");
                }
                else // no one in session
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return View("New");
            }
        }

        [HttpGet("BrightIdea/Like/{brightideaId}/{isLike}")]
        public IActionResult Like(int brightideaId, bool isLike)
        {
            if (!_isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            // if the post exists
            if (_db.BrightIdea.Any(brightidea => brightidea.BrightIdeaId == brightideaId))
            {
                Like foundLike = _db.Likes
                    .FirstOrDefault(like => like.UserId == _uid
                        && like.BrightIdeaId == brightideaId);

                if (foundLike == null)
                {
                    Like newLike = new Like
                    {
                        BrightIdeaId = brightideaId,
                        IsLike = isLike,
                        UserId = (int)_uid
                    };
                    _db.Likes.Add(newLike);
                }
                else // vote already exists
                {
                    // if new vote is same as existing vote
                    if (foundLike.IsLike == isLike)
                    {
                        _db.Remove(foundLike);
                    }
                    else // changing vote
                    {
                        foundLike.IsLike = isLike;
                    }
                }
                _db.SaveChanges();
            }
            return RedirectToAction("All");
        }

        // [HttpGet("Posts/Vote/{postId}/{isUpvote}")]
        // public IActionResult Vote(int postId, bool isUpvote)
        // {
        //     if (!_isLoggedIn)
        //     {
        //         return RedirectToAction("Index", "Home");
        //     }

        //     // if the post exists
        //     if (_db.Posts.Any(post => post.PostId == postId))
        //     {

        //         Vote foundVote = _db.Votes
        //             .FirstOrDefault(vote => vote.UserId == _uid 
        //             && vote.PostId == postId);

        //         if (foundVote != null)
        //         {
        //             _db.Votes.Remove(foundVote);
        //         }
        //          // if the first part of the || is true, the second part
                    // is not checked. This is needed because if the
                    // foundVote is null, we will get an error trying
                    // to access a property on it
        //         if (foundVote == null || foundVote.IsUpvote != isUpvote)
        //         {
        // Vote newVote = new Vote
        // {
        //     PostId = postId,
        //     IsUpvote = isUpvote,
        //     UserId = (int)_uid
        // };
        // _db.Votes.Add(newVote);
        //         }
        //         // save changes to save the potentialy
        //         // deletion and the potential new vote
        //         _db.SaveChanges();
        //     }
        // return RedirectToAction("All");
        // }

        [HttpGet("brightidea/delete/{id}")]
        public IActionResult Delete(int id)
        {
            BrightIdea brightideaFromDb = _db.BrightIdea.FirstOrDefault(brightidea => brightidea.BrightIdeaId == id);

            if (brightideaFromDb != null)
            {
                _db.BrightIdea.Remove(brightideaFromDb);
                _db.SaveChanges();
            }

            return RedirectToAction("All");
        }
    }
}

Views/BrightIdea/AliasDetails.cshtml
@model BrightIdea

<div class="card mx-auto text-center mb-3" style="width: 25rem;">
  <div class="card-header">
    <h5 class="card-title">
        @Model.Author.FullName()
    </h5>
    <h5 class="card-title">
        @Model.Author.Alias
    </h5>
    <h5 class="card-title">
        @Model.Author.Email
    </h5>
  </div>
<div class="card-footer">

    <a asp-controller="BrightIdea" asp-action="All" class="btn btn-info">
      Back
    </a>

    @if (ViewBag.Uid == Model.Author.UserId) {
      <a asp-controller="BrightIdea" asp-action="Delete" asp-route-id="@Model.BrightIdeaId" class="btn btn-danger">
        Delete
      </a>
    }
</div>
</div>

Views/BrightIdea/All.cshtml
@model List<BrightIdea>;


<a asp-action="logout" asp-controller="Home">LOGOUT</a>

<h5 class="text-center">
  <a href="new">Post something witty here...</a>
</h5>

<h1 class="text-center">
  All Bright Ideas
</h1>

@foreach (BrightIdea currentBrightIdea in Model)
{
<div class="card mx-auto text-center mb-3" style="width: 25rem;">
  <div class="card-header">
    <h5 class="card-title">
      <a asp-action="AliasDetails" asp-controller="BrightIdea" asp-route-idforaliasdetails="@currentBrightIdea.BrightIdeaId">@currentBrightIdea.Author.FullName()</a> says:
    </h5>
  </div>
  <div class="card-body">
    <p class="card-text">
      @currentBrightIdea.Content
    </p>
  </div>
  <div class="card-footer">
    @if (ViewBag.Uid == @currentBrightIdea.Author.UserId) {
      <a asp-controller="BrightIdea" asp-action="Delete" asp-route-id="@currentBrightIdea.BrightIdeaId" class="btn btn-danger">
        Delete
      </a>
    }
    @{
      Like currentLike = currentBrightIdea.Likes.FirstOrDefault(like => like.UserId == ViewBag.Uid);

      string upArrowClass = "text-muted";
      string downArrowClass = "text-muted";


      if (currentLike != null)
      {
        if (currentLike.IsLike)
        {
          upArrowClass = "text-success";
        }
        else
        {
          downArrowClass = "text-danger";
        }
      }
    }
    <a
      asp-controller="BrightIdea"
      asp-action="Like"
      asp-route-postId="@currentBrightIdea.BrightIdeaId"
      asp-route-isLike="true"
      class="h1 @upArrowClass"
      style="text-decoration: none;"
      >
      &uarr;
    </a>
    <a
      asp-controller="BrightIdea"
      asp-action="Like"
      asp-route-postId="@currentBrightIdea.BrightIdeaId"
      asp-route-isLike="false"
      class="h1 @downArrowClass"
      style="text-decoration: none;"
      >
      &darr;
    </a>
    <a asp-action="LikersDetails" asp-controller="BrightIdea" asp-route-idforlikersdetails="@currentBrightIdea.BrightIdeaId.">@currentBrightIdea.Likes.Count people</a> like this.
  </div>
</div>
}

Views/BrightIdea/LikersDetails.cshtml
@model BrightIdea

<div class="card mx-auto text-center mb-3" style="width: 25rem;">
  <div class="card-header">
    <h5 class="card-title">
        @Model.Author.FullName()
    </h5>
  </div>

<div class="card-body">
  <p class="card-text">
    @Model.Content
  </p>
  <p class="card-text">
    People who like this post:
  </p>
  <table class="table">
        <thead class="thead-dark">
            <th>Alias</th>
            <th>Name</th>
        </thead>
        <tbody>
            @foreach(var currentLiker in @Model.Likes){
            <tr>
                <td><a asp-action="AliasDetails" asp-controller="BrightIdea" asp-route-id="@Model.BrightIdeaId">@currentLiker.Liker.Alias</a></td>
                <td>@currentLiker.Liker.FullName()</td>
            </tr>
            }
        </tbody>
  </table>
</div>

<div class="card-footer">

    <a asp-controller="BrightIdea" asp-action="All" class="btn btn-info">
      Back
    </a>

    @if (ViewBag.Uid == Model.Author.UserId) {
      <a asp-controller="BrightIdea" asp-action="Delete" asp-route-id="@Model.BrightIdeaId" class="btn btn-danger">
        Delete
      </a>
    }
</div>
</div>

Views/BrightIdea/New.cshtml
@model BrightIdea

<h1>Post something witty here...</h1>

<form asp-controller="BrightIdea" asp-action="Create">

  <div class="form-group">
    <label asp-for="Content">
      Content
    </label>
    <span class="text-danger font-weight-bold" asp-validation-for="Content"></span>
    <input class="form-control" asp-for="Content">
  </div>
  <button class="btn btn-info" type="submit">Submit</button>

</form>